"""Curated community-style blocklists, grouped by category.

These mirror the kind of entries found in well-known public blocklists
(e.g. StevenBlack's hosts file, EasyList/EasyPrivacy) so users can enable
a whole category at once instead of adding domains one at a time.
"""

from typing import Any

PRESETS: dict[str, dict[str, Any]] = {
    "ads-marketing": {
        "name": "Ads & Marketing",
        "description": "Display, video, and native ad servers used across most ad-supported sites.",
        "domains": [
            "doubleclick.net",
            "googlesyndication.com",
            "googleadservices.com",
            "adservice.google.com",
            "google-analytics.com",
            "googletagservices.com",
            "googletagmanager.com",
            "adnxs.com",
            "adsafeprotected.com",
            "rubiconproject.com",
            "pubmatic.com",
            "openx.net",
            "casalemedia.com",
            "criteo.com",
            "criteo.net",
            "outbrain.com",
            "taboola.com",
            "media.net",
            "smartadserver.com",
            "adform.net",
            "teads.tv",
            "sharethrough.com",
            "indexexchange.com",
            "spotxchange.com",
            "gumgum.com",
            "sovrn.com",
            "bidswitch.net",
            "contextweb.com",
            "agkn.com",
            "tapad.com",
            "flashtalking.com",
            "sizmek.com",
            "adsrvr.org",
            "turn.com",
            "advertising.com",
            "yieldmo.com",
            "3lift.com",
            "yieldlab.net",
            "adtelligent.com",
            "aax.amazon-adsystem.com",
            "amazon-adsystem.com",
            "bat.bing.com",
            "ads.yahoo.com",
            "adtech.de",
        ],
    },
    "analytics-trackers": {
        "name": "Analytics & Trackers",
        "description": "Behavioral analytics, session replay, and cross-site tracking services.",
        "domains": [
            "scorecardresearch.com",
            "quantserve.com",
            "chartbeat.com",
            "chartbeat.net",
            "mixpanel.com",
            "segment.io",
            "segment.com",
            "hotjar.com",
            "fullstory.com",
            "mouseflow.com",
            "crazyegg.com",
            "amplitude.com",
            "heap.io",
            "heapanalytics.com",
            "kissmetrics.com",
            "optimizely.com",
            "clicktale.net",
            "inspectlet.com",
            "luckyorange.com",
            "krxd.net",
            "bluekai.com",
            "demdex.net",
            "rlcdn.com",
            "mathtag.com",
            "exelator.com",
            "nielsen.com",
            "comscore.com",
            "newrelic.com",
            "branch.io",
            "appsflyer.com",
            "adjust.com",
            "quantcast.com",
            "parsely.com",
            "cedexis.com",
            "clarity.ms",
        ],
    },
    "social-trackers": {
        "name": "Social Media Trackers",
        "description": "Tracking pixels and analytics beacons embedded by social platforms on third-party pages.",
        "domains": [
            "connect.facebook.net",
            "facebook.com/tr",
            "an.facebook.com",
            "ads-twitter.com",
            "analytics.twitter.com",
            "static.ads-twitter.com",
            "ct.pinterest.com",
            "log.pinterest.com",
            "px.ads.linkedin.com",
            "analytics.tiktok.com",
            "ads.tiktok.com",
            "tr.snapchat.com",
            "sc-static.net",
            "alb.reddit.com",
            "pixel.redditmedia.com",
            "events.redditmedia.com",
            "q.quora.com",
            "analytics.pinterest.com",
        ],
    },
    "aggressive-adnetworks": {
        "name": "Aggressive Ad Networks",
        "description": "Pop-under, redirect-heavy, and malvertising-prone ad networks best blocked outright.",
        "domains": [
            "popads.net",
            "popcash.net",
            "propellerads.com",
            "adcash.com",
            "exoclick.com",
            "juicyads.com",
            "trafficjunky.net",
            "adsterra.com",
            "hilltopads.net",
            "mgid.com",
            "revcontent.com",
            "content.ad",
            "clicksor.com",
            "adroll.com",
            "zedo.com",
            "onclickads.net",
            "adnium.com",
            "adskeeper.com",
        ],
    },
}


def preset_domain_count(preset_id: str) -> int:
    return len(PRESETS[preset_id]["domains"])
